// constants.ts — Centraliza feature flags e constantes globais da API
import { env } from './env'

export const MCP_ENABLED = env.MCP_ENABLED
export const API_RATE_LIMIT_PER_MINUTE = env.API_RATE_LIMIT_PER_MINUTE
export const WEBHOOK_PHONE_RATE_LIMIT_PER_MINUTE = env.WEBHOOK_PHONE_RATE_LIMIT_PER_MINUTE
export const BATCH_WINDOW_MS = env.BATCH_WINDOW_MS
export const BATCH_MAX_MESSAGES = env.BATCH_MAX_MESSAGES
export const QUEUE_CONCURRENCY = env.QUEUE_CONCURRENCY
export const AUDIO_ENABLED = env.AUDIO_ENABLED ?? env.AUDIO_AUTO_ENABLED
export const AUDIO_MAX_CHARS = env.AUDIO_MAX_CHARS
export const AUDIO_RANDOM_CHANCE = env.AUDIO_RANDOM_CHANCE
export const REACTIONS_ENABLED = env.REACTIONS_ENABLED
export const REACTIONS_MIN_INTERVAL_MINUTES = env.REACTIONS_MIN_INTERVAL_MINUTES
export const REACTIONS_ALLOWED_EMOJIS = env.REACTIONS_ALLOWED_EMOJIS
export const VAULT_COMPACTION_DELAY_MS = env.VAULT_COMPACTION_DELAY_MS
export const VAULT_MAX_SUMMARY_TOKENS = env.VAULT_MAX_SUMMARY_TOKENS
export const VAULT_COMPACTION_MODEL = env.VAULT_COMPACTION_MODEL
export const VAULT_CRON_SCHEDULE = env.VAULT_CRON_SCHEDULE
export const MAX_TOOL_ITERATIONS = 3
